spring.application.name=Vitrinelocal

# PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5432/vitrinelocal
spring.datasource.username=postgres
spring.datasource.password=9902

# JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload de imagens
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
